added tftp example and slight wording change
sel4devkit/seL4-DevKit-Doc pull request #14
Opened 2023-02-21 16:51 UTC by josh-felm

2023-02-21 16:51 UTC, josh-felm commented
merged with master

2023-02-23 09:23 UTC, adfw-c requested changes
General corrections look good. TFTP example needs a few minor changes but otherwise looks good too.

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/devkit_offline_use.md
> +Note that Git might request a username and email, which can be any string and does not have to be associated with a Git account.
It's repo, not git, in this context. Also I suspect it's any string providing you just want a read-only copy?

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +The most efficient way of booting from an image is to set up a TFTP server from which the board can read from. This removes the need to repeatedly flash an SD card with a new image, and instead the i
Regarding OS, specifically it's Debian because of the use of `apt`

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +1. [Dnsmasq](https://thekelleys.org.uk/dnsmasq/doc.html) provides a network infrastructure for small networks and is designed to be lightweight. The program can be installed using apt-get
apt-get is considered old fashioned these days, consider `apt` (and also on line 8). Perhaps also add "or whatever package manager your distribution provides".

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +![Command `ip addr` output](../figures/ip-addr-ethernet.png)
I would prefer embedded code listings formatted in markdown rather than images

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +where the values are replaced with those corresponding to the output of the `ip addr` command. The `dhcp-range` should act as a net mask to allow ip allocation to the board.
Pedantically, dhcp-range is not a net mask, it's a range of IP addresses which dnsmasq will allocate to devices.

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +![bootp-output](../figures/bootp-load.png)
Can this be an embedded code listing as well? It's also missing the `bootelf` bit.

2023-02-23 09:23 UTC, adfw-c commented on seL4-doc/src/appendices/tftpboot_example.md
> +![Command `ip addr` output](../figures/ip-addr-ethernet.png)
In the image, the ipv6 link-local is not obfuscated, and it's possible to derive the MAC address from it.

2024-04-30 13:18 UTC, merged